<?php
$storeid = Mage::app()->getStore()->getStoreId();
$sliderwidth = Mage::getStoreConfig('categorysection/categorydesign/imgwidth', $storeid);
$sliderheight = Mage::getStoreConfig('categorysection/categorydesign/imgheight', $storeid);
$userCss = (Mage::getStoreConfig('categorysection/categorydesign/userCss', $storeid) == 1) ? 'true' : 'false';
$transitionspeed = Mage::getStoreConfig('categorysection/categorydesign/transitionspeed', $storeid);
$duration = Mage::getStoreConfig('categorysection/categorydesign/duration', $storeid);
$showNavigation = (Mage::getStoreConfig('categorysection/categorydesign/showNavigation', $storeid) == 1) ? 'true' : 'false';
$navigationColor = Mage::getStoreConfig('categorysection/categorydesign/navigationColor', $storeid);
$navigationHoverColor = Mage::getStoreConfig('categorysection/categorydesign/navigationHoverColor', $storeid);
$navigationHighlightColor = Mage::getStoreConfig('categorysection/categorydesign/navigationHighlightColor', $storeid);
$navigationNumberColor = Mage::getStoreConfig('categorysection/categorydesign/navigationNumberColor', $storeid);
$positionNavigation = Mage::getStoreConfig('categorysection/categorydesign/positionNavigation', $storeid);
$navigationType = Mage::getStoreConfig('categorysection/categorydesign/navigationType', $storeid);
$showControl = (Mage::getStoreConfig('categorysection/categorydesign/showControl', $storeid) == 1) ? 'true' : 'false';
$controlColor = Mage::getStoreConfig('categorysection/categorydesign/controlColor', $storeid);
$controlBackgroundColor = Mage::getStoreConfig('categorysection/categorydesign/controlBackgroundColor', $storeid);
$positionControl = Mage::getStoreConfig('categorysection/categorydesign/positionControl', $storeid);
$transition = Mage::getStoreConfig('categorysection/categorydesign/transition', $storeid);
$showProgress = (Mage::getStoreConfig('categorysection/categorydesign/showProgress', $storeid) == 1) ? 'true' : 'false';
$progressColor = Mage::getStoreConfig('categorysection/categorydesign/progressColor', $storeid);
$pauseOnHover = (Mage::getStoreConfig('categorysection/categorydesign/pauseOnHover', $storeid) == 1) ? 'true' : 'false';
?>

<?php
$currCatid = Mage::registry('current_category')->getId();
$collection = Mage::helper('categoryslider')->getCategoryCollection($currCatid);
$cnt = count($collection);
$media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>
<?php if ($cnt > 0) { ?>
    <div id="my-slide">
        <?php
        foreach ($collection as $sliderData) {
            $title = $sliderData["title"];
            $alttext = $sliderData["alttext"];
            $description = $sliderData["description"];
            $showdesc = $sliderData["showdesc"];
            $catimg = $sliderData["image"];
            $imgurl = $media_url . $catimg;
            $showurl = $sliderData["showurl"];
            $url = $sliderData["url"];
            $target = ($sliderData["urltarget"] == '1') ? '_blank' : '_parent';
            ?>

            <div data-lazy-background="<?php echo $imgurl; ?>" class="slide2 primary-img background active" style="display: block; position: absolute; top: 0%; left: 0%; width: <?php echo $sliderwidth . 'px'; ?>; height: <?php echo $sliderheight . 'px'; ?>;">
                <?php if ($showurl) { ?>
                <a href="<?php echo $url; ?>" target="<?php echo $target; ?>">
                    <?php } ?>
                        <img class="lazy-background" alt="<?php echo $alttext; ?>" title="<?php echo $title; ?>" src="<?php echo $imgurl; ?>" style="top: 0px; left: 0px; width: 100%; height: 100%; z-index: -1;">
                    <?php if ($showurl) { ?>
                    </a>
                <?php } ?>
                <?php
                if ($showdesc) {
                    echo $description;
                }
                ?>
            </div>
            <?php
        }
        ?>
    </div>


    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('#my-slide').DrSlider({
                width: '<?php echo $sliderwidth ?>',
                height: '<?php echo $sliderheight ?>',
                userCSS: <?php echo $userCss ?>,
                transitionSpeed: <?php echo $transitionspeed ?>,
                duration: <?php echo $duration ?>,
                showNavigation: <?php echo $showNavigation ?>,
                navigationColor: '<?php echo '#' . $navigationColor ?>',
                navigationHoverColor: '<?php echo '#' . $navigationHoverColor ?>',
                navigationHighlightColor: '<?php echo '#' . $navigationHighlightColor ?>',
                navigationNumberColor: '<?php echo '#' . $navigationNumberColor ?>',
                positionNavigation: '<?php echo $positionNavigation ?>',
                navigationType: '<?php echo $navigationType ?>',
                showControl: <?php echo $showControl ?>,
                controlColor: '<?php echo '#' . $controlColor ?>',
                controlBackgroundColor: '<?php echo '#' . $controlBackgroundColor ?>',
                positionControl: '<?php echo $positionControl ?>',
                transition: '<?php echo $transition ?>',
                showProgress: <?php echo $showProgress ?>,
                progressColor: '<?php echo '#' . $progressColor ?>',
                pauseOnHover: <?php echo $pauseOnHover ?>
            });
        });
    </script>
<?php } ?>